import { type NextPage } from "next";
import Head from "next/head";

const Dish: NextPage = () => {

  return (
    <>
      <Head>
        <title>Food Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col h-screen">

        <div>Slug</div>

      </main>
    </>
  );
};

export default Dish;
