import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { create } from "domain";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [active, setActive] = useState("eat");
  const [dishName, setDishName] = useState("");
  const [dishUrl, setDishUrl] = useState("");
  const user = useUser();

  const {data} = api.dish.getAllDishes.useQuery();

  const {mutate} = api.dish.create.useMutation();

  if (!user) return null;

  return (
    <>
      <Head>
        <title>Food Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col h-screen">
        <div>
        </div>

        <div className="flex flex-col flex-initial items-center w-11/12 ml-0 grow">
          {active === "eat" && 
            <div className="grid grid-cols-2 flex-1 gap-4 w-full pt-4 pb-4">
              {data?.map((dish) => (
                <div key={dish.id} className="card group" style={{backgroundImage: 'url('+ dish.url +')'}}>
                  <span className="heading">{dish.name}</span>
                </div>
              ))}
            </div>
          }
          {active === "add" && 
            <div className="flex flex-col flex-1 justify-end">
              <div className="input-wrapper">
                <input id="nameInput" className="peer input" value={dishName} placeholder=" "onChange={(e) => setDishName(e.target.value)}/>
                <label className="input-label before:content[' '] after:content[' ']">
                  Gerichtname
                </label>
              </div>
            
              <div className="input-wrapper">
                <input id="urlInput" className="peer input" value={dishUrl} placeholder=" " onChange={(e) => setDishUrl(e.target.value)}/>
                <label className="input-label before:content[' '] after:content[' ']">
                  Bild URL
                </label>
              </div>

              <button className="submit-button mb-6" onClick={() => mutate({name: dishName, url: dishUrl})}>
                Speichern
              </button>
            </div>
          }
        </div>

        <div className="flex flex-row items-center order-last">
          <div>
            {user.isSignedIn && 
              <div className="flex flex-initial flex-row gap-6 text-right border-t-4 pt-2">
                <div className={active === "eat" ? "menu-entry text-blue-600" : "menu-entry"}><a onClick={() => setActive("eat")}>Food</a></div>
                <div className={active === "history" ? "menu-entry text-blue-600" : "menu-entry"}><a onClick={() => setActive("history")}>Help</a></div>
                <div className={active === "add" ? "menu-entry text-blue-600 pb-0" : "menu-entry pb-0"}><a onClick={() => setActive("add")}>Add</a></div>
                <div className="menu-entry">{<SignOutButton/>}</div>
              </div>
            }
            {!user.isSignedIn && 
              <div className="flex flex-initial flex-row gap-6 text-right border-t-4 pt-2">
                <div className="menu-entry text-blue-600"><a>Beispiel</a></div>
                <div className="menu-entry">{<SignInButton/>}</div>
              </div>
            }
          </div> 
        </div>

      </main>
    </>
  );
};

export default Home;
