import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { LoadingPage, LoadingSpinner } from "~/components/loading";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [active, setActive] = useState("eat");
  const [dishName, setDishName] = useState("");
  const [dishUrl, setDishUrl] = useState("");
  const [posted, setPosted] = useState(false);
  const [error, setError] = useState(false);
  const [infoText, setInfoText] = useState("");
  const [page, setPage] = useState(0);  
  const user = useUser();

  const {mutate, isLoading: isPosting, isError} = api.dish.create.useMutation({
    onSuccess: () => {
      setPosted(true);
      setDishName("");
      setDishUrl("");
      setTimeout(() => {
        setPosted(false);
      }, 2500);
    }, onError: (e) => {
      setError(true);

      setTimeout(() => {
        setError(false)
      }, 2500);
    }
  });

  const {data, fetchNextPage, isLoading} = api.dish.getDishesByUserId.useInfiniteQuery(
    {
      limit: 8,
    },
    {
      getNextPageParam: (lastPage) => lastPage.nextCursor,
    }
  );

  const handleFetchNextPage = async () => {
    await fetchNextPage();

    if (data?.pages[page]?.nextCursor === undefined) {
      setPage((prev) => prev - 1);
    } else {
      setPage((prev) => prev + 1);
    }
  };

  if (isLoading) return <LoadingPage/>

  if (!user) return null;

  return (
    <>
      <Head>
        <title>Food Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center flex-col h-screen">
        <div>
        </div>

        <div className="flex flex-col flex-initial items-center w-11/12 h-full ml-0">
          {active === "eat" && 
            <div className="w-full">
              <div className="grid grid-cols-2 flex-1 gap-4 pt-4 pb-4">
                {data?.pages[page]?.dishes.map((dish) => (
                  <div key={dish.id} className="card group" style={{backgroundImage: 'url('+ dish.url +')'}}>
                    <span className="heading">{dish.name}</span>
                  </div>
                ))}
              </div>
              <div className="w-fit m-auto hover:rotate-180 active:scale-95 transition-all duration-200">
                <a className="text-2xl cursor-pointer" onClick={() => void handleFetchNextPage()}>🔄</a>
              </div>
            </div>
          }

          {active === "add" && 
            <div className="flex flex-col flex-1 justify-end">
              <div className="input-wrapper">
                <input id="nameInput" 
                className="peer input" 
                value={dishName} 
                placeholder=" " 
                onChange={(e) => setDishName(e.target.value)}
                disabled={isPosting}/>
                <label className="input-label before:content[' '] after:content[' ']">
                  Gerichtname
                </label>
              </div>
            
              <div className="input-wrapper">
                <input id="urlInput" 
                className="peer input" 
                value={dishUrl} 
                placeholder=" " 
                onChange={(e) => setDishUrl(e.target.value)}
                disabled={isPosting}/>
                <label className="input-label before:content[' '] after:content[' ']">
                  Bild URL
                </label>
              </div>

              {(!isPosting && !posted && !error) && 
                <button className="submit-button mb-6" 
                onClick={() => mutate({name: dishName, url: dishUrl})}>
                  Speichern
                </button>
              }
              {isPosting && 
                <button className="submit-button py-1 mb-6" 
                disabled={isPosting}>
                  {<LoadingSpinner size={28}/>}
                </button>
              }
              {posted && 
                <button className="submit-button bg-green-600 hover:shadow-green-500/40 shadow-blue-500/20 text-2xl py-1 mb-6" 
                disabled={isPosting}>
                  ✅
                </button>
              }
              {error && 
                <button className="submit-button bg-red-700 hover:shadow-red-600/40 shadow-red-500/20 text-2xl py-1 mb-6" 
                disabled={isPosting}>
                  ❌
                </button>
              }
            </div>
          }
        </div>

        <div className="flex flex-row items-center order-last">
          <div>
            {user.isSignedIn && 
              <div className="flex flex-initial flex-row gap-6 text-right border-t-4 pt-2">
                <div className={active === "eat" ? "menu-entry text-blue-600" : "menu-entry"}><a onClick={() => setActive("eat")}>Food</a></div>
                <div className={active === "history" ? "menu-entry text-blue-600" : "menu-entry"}><a onClick={() => setActive("history")}>Help</a></div>
                <div className={active === "add" ? "menu-entry text-blue-600 pb-0" : "menu-entry pb-0"}><a onClick={() => setActive("add")}>Add</a></div>
                <div className="menu-entry">{<SignOutButton/>}</div>
              </div>
            }
            {!user.isSignedIn && 
              <div className="flex flex-initial flex-row gap-6 text-right border-t-4 pt-2">
                <div className="menu-entry text-blue-600"><a>Beispiel</a></div>
                <div className="menu-entry">{<SignInButton/>}</div>
              </div>
            }
          </div> 
        </div>

      </main>
    </>
  );
};

export default Home;
